[URLs]
LOGIN_URL = https://www.saucedemo.com/

[Selectors]
USERNAME_INPUT = #user-name
PASSWORD_INPUT = #password
LOGIN_BUTTON = #login-button
INVENTORY_PAGE_INDICATOR = #inventory_container
LOGOUT_BUTTON = #logout_sidebar_link